version: '3.8'

services:
  web:
    build: .
    ports:
      - "443:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    volumes:
      - ./ssl:/ssl

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linky-pie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: